// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agwoqxwrcvuwztagpwqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnd29xeHdyY3Z1d3p0YWdwd3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTA4MzIsImV4cCI6MjA2NTQ4NjgzMn0.kVrJ6soy5Af-IKMG0OVxDgyeoygBgkS7s8ubPjmfttU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);